### ISSUE TITLE
Job>taskstatus is not included in the FMC class

### ISSUE THREAD

**Issue by gsin0080** [kaisero/fireREST#47]
FMC version 6.6

As title, the job.taskstatus is not declared in the FMC class.  Please add it to the FMC class.

Also, this taskstatus API endpoint on FMC doesn't like the query parameters at the back.  I realise the code adds "?limit=1000&expanded=True" at the end by default.  Please update the resource to not adding any query parameters for taskstatus.

My workaround for this API endpoint at the moment:
taskStatusURL = "https://"+hostname+"/api/fmc_config/v1/domain/"+fmc.domain['id']+"/job/taskstatuses/"+taskId
response = fmc.conn.get(taskStatusURL,None,1)

It might not be perfect, but it works.

**Comment by kaisero** [comment]
Thanks for the report and provided details. Looks like there were a variety of issues, starting from the fact that `Job` object was not part of `FMC` but also an incorrect api call to taskstatuses plus the possibility to execute non-GETBYID operations. Since the taskstatuses api only supports access to specific tasks I adapted the implementation to reflect that. Taskstatus can be queried in v1.0.5 which will be online soon.
